import modules.menu as m

def main():
    m.menu()

main()

"""
OE BRO:
TE DEJE TODO EL CRUD DEL JSON Y EXTRA A ESO TE DEJE MI REPO PARA QUE VEAS COMO SE HACE LA CONEXION BESITOS EN EL ANO
Y TE ARREGLE EL ERROR DE QUE NO ARRANQUE, COLOCA TUS CREDENCIALES Y MANDA ESTE COMMIT "ci: :beers: como es pa unas polas carlos att el rolo" ES IMPORTANTE QUE QUEDE IGUAL SI NO SE DAÑA EL REPO, REPITO COPEA Y PEGA SIN EDITAR EL COMMIT.

ATT: EL ROLO TE QUIERE MUCHO 💔
"""